### ISSUE TITLE
Request to reduce the confirmation delay

### ISSUE THREAD

**Issue by CloudeLecaw** [blablubbabc/HomeStations#4]
Well.. its not abug its more a confusing thing how the confirm is handles.

Example:
1. You press the lower button and get asked to confim this. -> OK
2. you decides to to some other things now..may place some blocks or sing a song... -> OK (why not ^^)
3. You press the lower button and now....you should get asked to confim this aggain... but no.. you get the information that your entry is confirmed... -> why?

Problem: There is no confiurable time when the confirm is cancelt if u decide to not do it direclty..or withing a few secounds..
 normaly a defineable time after that it should be cancel it ...or maybe better.... if you do some other interaction then the confirming (move away, interact with other button, place a block, mine a block, what ever you can do) then it should cancels the confirmation and u have to start again if u want to "set" the homestation

What i tested allready...

- i pressed the lower button once (got asked to confirm)
- placed some blocks
- went to toilet
- comeback and used homestation to spawn and back
- pressed lower button once...and... it was confirmed now even if it normaly should be the first presstime now after this long time...but no...it got saved somewhere. the confirm only seem to count as new "firstpress" if u press the lower button of another station.

**Comment by blablubbabc** [comment]
There is a 20 seconds delay. I just tested, and that works for me. The only way you can bypass that is by disabling confirmations alltogether by clearing the corresponding confirmation message (this might actually not work right now.. but shouldn't affect the delay), and by changing the system time backwards.

**Comment by CloudeLecaw** [comment]
is is possible to lower this delay (may a "new" config value? :)

**Comment by blablubbabc** [comment]
What would you set it to? I feel like there should not be much need to configure it, if it is set accordingly.

**Comment by CloudeLecaw** [comment]
yes i know, ist just that 20 secounds feel for the Players like an endless amount of time 🥉 
ist the same button they have to confirm… so a max of may 5 sec would be more then enough..
as longer as this time is, the Players began to Play do other Things and then start to wonder.

**Comment by blablubbabc** [comment]
I have changed it to 10 seconds as a compromise. That should also be enough time to read and verify the confirmation message (which might even involve vault economy costs for teleporting).
The change will be included in the next update (no ETA on that though).
